// Code generated by "stringer -type=ParamType,ReturnType,TestItem,TestDataKind"; DO NOT EDIT.

package helper

import "strconv"

const _ParamType_name = "ParamBelowParamNoneParamArgParamArgsParamSliceParamSetParamIJParamAbove"

var _ParamType_index = [...]uint8{0, 10, 19, 27, 36, 46, 54, 61, 71}

func (i ParamType) String() string {
	if i >= ParamType(len(_ParamType_index)-1) {
		return "ParamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParamType_name[_ParamType_index[i]:_ParamType_index[i+1]]
}

const _ReturnType_name = "ReturnBelowReturnNoneReturnBoolReturnIntReturnInterfaceReturnJSONReturnStringReturnSetReturnSliceReturnSliceOfStringsReturnAbove"

var _ReturnType_index = [...]uint8{0, 11, 21, 31, 40, 55, 65, 77, 86, 97, 117, 128}

func (i ReturnType) String() string {
	if i >= ReturnType(len(_ReturnType_index)-1) {
		return "ReturnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReturnType_name[_ReturnType_index[i]:_ReturnType_index[i+1]]
}

const _TestItem_name = "AB"

var _TestItem_index = [...]uint8{0, 1, 2}

func (i TestItem) String() string {
	if i >= TestItem(len(_TestItem_index)-1) {
		return "TestItem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestItem_name[_TestItem_index[i]:_TestItem_index[i+1]]
}

const _TestDataKind_name = "InOut"

var _TestDataKind_index = [...]uint8{0, 2, 5}

func (i TestDataKind) String() string {
	if i >= TestDataKind(len(_TestDataKind_index)-1) {
		return "TestDataKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestDataKind_name[_TestDataKind_index[i]:_TestDataKind_index[i+1]]
}
