// Code generated by "stringer -type=ValPathItemType"; DO NOT EDIT.

package bw

import "strconv"

const _ValPathItemType_name = "ValPathItemHashValPathItemIdxValPathItemKeyValPathItemPathValPathItemVar"

var _ValPathItemType_index = [...]uint8{0, 15, 29, 43, 58, 72}

func (i ValPathItemType) String() string {
	if i >= ValPathItemType(len(_ValPathItemType_index)-1) {
		return "ValPathItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValPathItemType_name[_ValPathItemType_index[i]:_ValPathItemType_index[i+1]]
}
