#!/bin/sh
go get github.com/baza-winner/bwcore/ansi
go get github.com/baza-winner/bwcore/bw
go get github.com/baza-winner/bwcore/bwdebug
go get github.com/baza-winner/bwcore/bwerr
go get github.com/baza-winner/bwcore/bwexec
go get github.com/baza-winner/bwcore/bwjson
go get github.com/baza-winner/bwcore/bwmap
go get github.com/baza-winner/bwcore/bwos
go get github.com/baza-winner/bwcore/bwparse
go get github.com/baza-winner/bwcore/bwrune
go get github.com/baza-winner/bwcore/bwset
go get github.com/baza-winner/bwcore/bwsetter
go get github.com/baza-winner/bwcore/bwstr
go get github.com/baza-winner/bwcore/bwtesting
go get github.com/baza-winner/bwcore/bwtype
go get github.com/baza-winner/bwcore/bwval
go get github.com/mohae/deepcopy
go get github.com/urfave/cli
go get github.com/maruel/panicparse/cmd/pp
go get golang.org/x/tools/cmd/stringer
go get github.com/iancoleman/strcase
go get honnef.co/go/tools/cmd/megacheck
