// Code generated by "bwsetter -type=float64"; DO NOT EDIT; bwsetter: go get -type=float64 -set=Float64 -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	"encoding/json"
	"sort"
	"strconv"
)

// Float64 - множество значений типа float64 с поддержкой интерфейсов Stringer и MarshalJSON
type Float64 map[float64]struct{}

// Float64From - конструктор Float64
func Float64From(kk ...float64) Float64 {
	result := Float64{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Float64FromSlice - конструктор Float64
func Float64FromSlice(kk []float64) Float64 {
	result := Float64{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Float64FromSet - конструктор Float64
func Float64FromSet(s Float64) Float64 {
	result := Float64{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Float64) Copy() Float64 {
	return Float64FromSet(v)
}

// ToSlice - возвращает в виде []float64
func (v Float64) ToSlice() []float64 {
	result := _float64Slice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _Float64ToSliceTestHelper(kk []float64) []float64 {
	return Float64FromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Float64) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v Float64) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Float64) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatFloat(float64(k), byte(0x66), -1, 64))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Float64) Has(k float64) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Float64) HasAny(kk ...float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Float64) HasAnyOfSlice(kk []float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Float64) HasAnyOfSet(s Float64) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Float64) HasEach(kk ...float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Float64) HasEachOfSlice(kk []float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Float64) HasEachOfSet(s Float64) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Float64) Add(kk ...float64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Float64) _AddTestHelper(kk ...float64) Float64 {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Float64) AddSlice(kk []float64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Float64) _AddSliceTestHelper(kk []float64) Float64 {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Float64) AddSet(s Float64) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Float64) _AddSetTestHelper(s Float64) Float64 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Float64) Del(kk ...float64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Float64) _DelTestHelper(kk ...float64) Float64 {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Float64) DelSlice(kk []float64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Float64) _DelSliceTestHelper(kk []float64) Float64 {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Float64) DelSet(s Float64) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Float64) _DelSetTestHelper(s Float64) Float64 {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Float64) Union(s Float64) Float64 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Float64) Intersect(s Float64) Float64 {
	result := Float64{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Float64) Subtract(s Float64) Float64 {
	result := Float64{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _float64Slice []float64

func (v _float64Slice) Len() int {
	return len(v)
}

func (v _float64Slice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _float64Slice) Less(i int, j int) bool {
	return v[i] < v[j]
}
