// Code generated by "bwsetter -type=int32"; DO NOT EDIT; bwsetter: go get -type=int32 -set=Int32 -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	"encoding/json"
	"sort"
	"strconv"
)

// Int32 - множество значений типа int32 с поддержкой интерфейсов Stringer и MarshalJSON
type Int32 map[int32]struct{}

// Int32From - конструктор Int32
func Int32From(kk ...int32) Int32 {
	result := Int32{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Int32FromSlice - конструктор Int32
func Int32FromSlice(kk []int32) Int32 {
	result := Int32{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Int32FromSet - конструктор Int32
func Int32FromSet(s Int32) Int32 {
	result := Int32{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Int32) Copy() Int32 {
	return Int32FromSet(v)
}

// ToSlice - возвращает в виде []int32
func (v Int32) ToSlice() []int32 {
	result := _int32Slice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _Int32ToSliceTestHelper(kk []int32) []int32 {
	return Int32FromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Int32) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v Int32) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Int32) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatInt(int64(k), 10))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Int32) Has(k int32) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int32) HasAny(kk ...int32) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int32) HasAnyOfSlice(kk []int32) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int32) HasAnyOfSet(s Int32) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int32) HasEach(kk ...int32) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int32) HasEachOfSlice(kk []int32) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int32) HasEachOfSet(s Int32) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Int32) Add(kk ...int32) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Int32) _AddTestHelper(kk ...int32) Int32 {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Int32) AddSlice(kk []int32) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Int32) _AddSliceTestHelper(kk []int32) Int32 {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Int32) AddSet(s Int32) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Int32) _AddSetTestHelper(s Int32) Int32 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Int32) Del(kk ...int32) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Int32) _DelTestHelper(kk ...int32) Int32 {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Int32) DelSlice(kk []int32) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Int32) _DelSliceTestHelper(kk []int32) Int32 {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Int32) DelSet(s Int32) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Int32) _DelSetTestHelper(s Int32) Int32 {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Int32) Union(s Int32) Int32 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Int32) Intersect(s Int32) Int32 {
	result := Int32{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Int32) Subtract(s Int32) Int32 {
	result := Int32{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _int32Slice []int32

func (v _int32Slice) Len() int {
	return len(v)
}

func (v _int32Slice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _int32Slice) Less(i int, j int) bool {
	return v[i] < v[j]
}
