// Code generated by "bwsetter -type=int"; DO NOT EDIT; bwsetter: go get -type=int -set=Int -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	"encoding/json"
	"sort"
	"strconv"
)

// Int - множество значений типа int с поддержкой интерфейсов Stringer и MarshalJSON
type Int map[int]struct{}

// IntFrom - конструктор Int
func IntFrom(kk ...int) Int {
	result := Int{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// IntFromSlice - конструктор Int
func IntFromSlice(kk []int) Int {
	result := Int{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// IntFromSet - конструктор Int
func IntFromSet(s Int) Int {
	result := Int{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Int) Copy() Int {
	return IntFromSet(v)
}

// ToSlice - возвращает в виде []int
func (v Int) ToSlice() []int {
	result := _intSlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _IntToSliceTestHelper(kk []int) []int {
	return IntFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Int) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v Int) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Int) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatInt(int64(k), 10))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Int) Has(k int) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int) HasAny(kk ...int) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int) HasAnyOfSlice(kk []int) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int) HasAnyOfSet(s Int) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int) HasEach(kk ...int) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int) HasEachOfSlice(kk []int) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int) HasEachOfSet(s Int) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Int) Add(kk ...int) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Int) _AddTestHelper(kk ...int) Int {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Int) AddSlice(kk []int) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Int) _AddSliceTestHelper(kk []int) Int {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Int) AddSet(s Int) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Int) _AddSetTestHelper(s Int) Int {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Int) Del(kk ...int) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Int) _DelTestHelper(kk ...int) Int {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Int) DelSlice(kk []int) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Int) _DelSliceTestHelper(kk []int) Int {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Int) DelSet(s Int) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Int) _DelSetTestHelper(s Int) Int {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Int) Union(s Int) Int {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Int) Intersect(s Int) Int {
	result := Int{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Int) Subtract(s Int) Int {
	result := Int{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _intSlice []int

func (v _intSlice) Len() int {
	return len(v)
}

func (v _intSlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _intSlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
