// Code generated by "bwsetter -type=string"; DO NOT EDIT; bwsetter: go get -type=string -set=String -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	"encoding/json"
	"sort"
)

// String - множество значений типа string с поддержкой интерфейсов Stringer и MarshalJSON
type String map[string]struct{}

// StringFrom - конструктор String
func StringFrom(kk ...string) String {
	result := String{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// StringFromSlice - конструктор String
func StringFromSlice(kk []string) String {
	result := String{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// StringFromSet - конструктор String
func StringFromSet(s String) String {
	result := String{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v String) Copy() String {
	return StringFromSet(v)
}

// ToSlice - возвращает в виде []string
func (v String) ToSlice() []string {
	result := _stringSlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _StringToSliceTestHelper(kk []string) []string {
	return StringFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v String) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v String) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v String) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v String) Has(k string) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v String) HasAny(kk ...string) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v String) HasAnyOfSlice(kk []string) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v String) HasAnyOfSet(s String) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v String) HasEach(kk ...string) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v String) HasEachOfSlice(kk []string) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v String) HasEachOfSet(s String) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v String) Add(kk ...string) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v String) _AddTestHelper(kk ...string) String {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v String) AddSlice(kk []string) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v String) _AddSliceTestHelper(kk []string) String {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v String) AddSet(s String) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v String) _AddSetTestHelper(s String) String {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v String) Del(kk ...string) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v String) _DelTestHelper(kk ...string) String {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v String) DelSlice(kk []string) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v String) _DelSliceTestHelper(kk []string) String {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v String) DelSet(s String) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v String) _DelSetTestHelper(s String) String {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v String) Union(s String) String {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v String) Intersect(s String) String {
	result := String{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v String) Subtract(s String) String {
	result := String{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _stringSlice []string

func (v _stringSlice) Len() int {
	return len(v)
}

func (v _stringSlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _stringSlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
