// Code generated by "bwsetter -type=uint64"; DO NOT EDIT; bwsetter: go get -type=uint64 -set=Uint64 -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	"encoding/json"
	"sort"
	"strconv"
)

// Uint64 - множество значений типа uint64 с поддержкой интерфейсов Stringer и MarshalJSON
type Uint64 map[uint64]struct{}

// Uint64From - конструктор Uint64
func Uint64From(kk ...uint64) Uint64 {
	result := Uint64{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Uint64FromSlice - конструктор Uint64
func Uint64FromSlice(kk []uint64) Uint64 {
	result := Uint64{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Uint64FromSet - конструктор Uint64
func Uint64FromSet(s Uint64) Uint64 {
	result := Uint64{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Uint64) Copy() Uint64 {
	return Uint64FromSet(v)
}

// ToSlice - возвращает в виде []uint64
func (v Uint64) ToSlice() []uint64 {
	result := _uint64Slice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _Uint64ToSliceTestHelper(kk []uint64) []uint64 {
	return Uint64FromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Uint64) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v Uint64) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Uint64) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatUint(uint64(k), 10))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Uint64) Has(k uint64) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Uint64) HasAny(kk ...uint64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Uint64) HasAnyOfSlice(kk []uint64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Uint64) HasAnyOfSet(s Uint64) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Uint64) HasEach(kk ...uint64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Uint64) HasEachOfSlice(kk []uint64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Uint64) HasEachOfSet(s Uint64) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Uint64) Add(kk ...uint64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Uint64) _AddTestHelper(kk ...uint64) Uint64 {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Uint64) AddSlice(kk []uint64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Uint64) _AddSliceTestHelper(kk []uint64) Uint64 {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Uint64) AddSet(s Uint64) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Uint64) _AddSetTestHelper(s Uint64) Uint64 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Uint64) Del(kk ...uint64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Uint64) _DelTestHelper(kk ...uint64) Uint64 {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Uint64) DelSlice(kk []uint64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Uint64) _DelSliceTestHelper(kk []uint64) Uint64 {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Uint64) DelSet(s Uint64) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Uint64) _DelSetTestHelper(s Uint64) Uint64 {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Uint64) Union(s Uint64) Uint64 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Uint64) Intersect(s Uint64) Uint64 {
	result := Uint64{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Uint64) Subtract(s Uint64) Uint64 {
	result := Uint64{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _uint64Slice []uint64

func (v _uint64Slice) Len() int {
	return len(v)
}

func (v _uint64Slice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _uint64Slice) Less(i int, j int) bool {
	return v[i] < v[j]
}
