// Code generated by "bwsetter -type=uint16"; DO NOT EDIT; bwsetter: go get -type=uint16 -set=Uint16 -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	"encoding/json"
	"sort"
	"strconv"
)

// Uint16 - множество значений типа uint16 с поддержкой интерфейсов Stringer и MarshalJSON
type Uint16 map[uint16]struct{}

// Uint16From - конструктор Uint16
func Uint16From(kk ...uint16) Uint16 {
	result := Uint16{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Uint16FromSlice - конструктор Uint16
func Uint16FromSlice(kk []uint16) Uint16 {
	result := Uint16{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Uint16FromSet - конструктор Uint16
func Uint16FromSet(s Uint16) Uint16 {
	result := Uint16{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Uint16) Copy() Uint16 {
	return Uint16FromSet(v)
}

// ToSlice - возвращает в виде []uint16
func (v Uint16) ToSlice() []uint16 {
	result := _uint16Slice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _Uint16ToSliceTestHelper(kk []uint16) []uint16 {
	return Uint16FromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Uint16) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v Uint16) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Uint16) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatUint(uint64(k), 10))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Uint16) Has(k uint16) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Uint16) HasAny(kk ...uint16) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Uint16) HasAnyOfSlice(kk []uint16) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Uint16) HasAnyOfSet(s Uint16) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Uint16) HasEach(kk ...uint16) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Uint16) HasEachOfSlice(kk []uint16) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Uint16) HasEachOfSet(s Uint16) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Uint16) Add(kk ...uint16) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Uint16) _AddTestHelper(kk ...uint16) Uint16 {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Uint16) AddSlice(kk []uint16) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Uint16) _AddSliceTestHelper(kk []uint16) Uint16 {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Uint16) AddSet(s Uint16) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Uint16) _AddSetTestHelper(s Uint16) Uint16 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Uint16) Del(kk ...uint16) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Uint16) _DelTestHelper(kk ...uint16) Uint16 {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Uint16) DelSlice(kk []uint16) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Uint16) _DelSliceTestHelper(kk []uint16) Uint16 {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Uint16) DelSet(s Uint16) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Uint16) _DelSetTestHelper(s Uint16) Uint16 {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Uint16) Union(s Uint16) Uint16 {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Uint16) Intersect(s Uint16) Uint16 {
	result := Uint16{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Uint16) Subtract(s Uint16) Uint16 {
	result := Uint16{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _uint16Slice []uint16

func (v _uint16Slice) Len() int {
	return len(v)
}

func (v _uint16Slice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _uint16Slice) Less(i int, j int) bool {
	return v[i] < v[j]
}
