// Code generated by "stringer -type ValKind -trimprefix Val"; DO NOT EDIT.

package bwtype

import "strconv"

const _ValKind_name = "UnknownStringIdBoolIntUintFloat64NumberPathRangeMapArrayNil"

var _ValKind_index = [...]uint8{0, 7, 13, 15, 19, 22, 26, 33, 39, 43, 48, 51, 56, 59}

func (i ValKind) String() string {
	if i >= ValKind(len(_ValKind_index)-1) {
		return "ValKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValKind_name[_ValKind_index[i]:_ValKind_index[i+1]]
}
