// Code generated by "bwsetter -type=ValKind"; DO NOT EDIT; bwsetter: go get -type=ValKind -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwval

import (
	"encoding/json"
	"sort"
)

// ValKindSet - множество значений типа ValKind с поддержкой интерфейсов Stringer и MarshalJSON
type ValKindSet map[ValKind]struct{}

// ValKindSetFrom - конструктор ValKindSet
func ValKindSetFrom(kk ...ValKind) ValKindSet {
	result := ValKindSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// ValKindSetFromSlice - конструктор ValKindSet
func ValKindSetFromSlice(kk []ValKind) ValKindSet {
	result := ValKindSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// ValKindSetFromSet - конструктор ValKindSet
func ValKindSetFromSet(s ValKindSet) ValKindSet {
	result := ValKindSet{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v ValKindSet) Copy() ValKindSet {
	return ValKindSetFromSet(v)
}

// ToSlice - возвращает в виде []ValKind
func (v ValKindSet) ToSlice() []ValKind {
	result := _ValKindSlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _ValKindSetToSliceTestHelper(kk []ValKind) []ValKind {
	return ValKindSetFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v ValKindSet) String() string {
	result, _ := json.Marshal(v)
	return string(result)
}

// MarshalJSON - поддержка интерфейса MarshalJSON
func (v ValKindSet) MarshalJSON() ([]byte, error) {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k)
	}
	return json.Marshal(result)
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v ValKindSet) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, k.String())
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v ValKindSet) Has(k ValKind) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v ValKindSet) HasAny(kk ...ValKind) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v ValKindSet) HasAnyOfSlice(kk []ValKind) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v ValKindSet) HasAnyOfSet(s ValKindSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v ValKindSet) HasEach(kk ...ValKind) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v ValKindSet) HasEachOfSlice(kk []ValKind) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v ValKindSet) HasEachOfSet(s ValKindSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v ValKindSet) Add(kk ...ValKind) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v ValKindSet) _AddTestHelper(kk ...ValKind) ValKindSet {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v ValKindSet) AddSlice(kk []ValKind) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v ValKindSet) _AddSliceTestHelper(kk []ValKind) ValKindSet {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v ValKindSet) AddSet(s ValKindSet) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v ValKindSet) _AddSetTestHelper(s ValKindSet) ValKindSet {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v ValKindSet) Del(kk ...ValKind) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v ValKindSet) _DelTestHelper(kk ...ValKind) ValKindSet {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v ValKindSet) DelSlice(kk []ValKind) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v ValKindSet) _DelSliceTestHelper(kk []ValKind) ValKindSet {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v ValKindSet) DelSet(s ValKindSet) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v ValKindSet) _DelSetTestHelper(s ValKindSet) ValKindSet {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v ValKindSet) Union(s ValKindSet) ValKindSet {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v ValKindSet) Intersect(s ValKindSet) ValKindSet {
	result := ValKindSet{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v ValKindSet) Subtract(s ValKindSet) ValKindSet {
	result := ValKindSet{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _ValKindSlice []ValKind

func (v _ValKindSlice) Len() int {
	return len(v)
}

func (v _ValKindSlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _ValKindSlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
